
drop table task if exists

drop table user_dto if exists 

 

create table task (task_id integer generated by default as identity (start with 1), task_desc varchar(255), task_name varchar(255), task_status varchar(255), user_id integer, primary key (task_id))

create table user_dto (user_id integer not null, user_name varchar(255), primary key (user_id))
 
